"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { renderMarkdownToHtml } from "@/lib/markdown";
import {
  Pencil,
  Sparkles,
  Check,
  X,
  Loader2,
  Undo2,
  ChevronDown,
  ChevronRight,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TreePhoto {
  id: string;
  url: string;
  caption?: string | null;
  category?: string | null;
}

interface TreeRecord {
  treeNumber: number;
  speciesCommon: string;
  treePhotos?: TreePhoto[];
}

export interface ParsedSection {
  id: string;
  title: string;
  level: number;
  content: string; // raw markdown for this section (including heading)
  body: string; // markdown body without the heading line
}

interface SectionEditorProps {
  content: string;
  reportId: string;
  trees: TreeRecord[];
  onContentChange: (newContent: string) => void;
  readOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/**
 * Split report markdown into sections by ## and ### headings.
 * Each section includes its heading + all content until the next heading
 * of the same or higher level.
 */
export function parseIntoSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let currentTitle = "";
  let currentLevel = 0;
  let currentLines: string[] = [];
  let preambleLines: string[] = [];
  let hasPreamble = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const h1Match = line.match(/^# (.+)/);
    const h2Match = line.match(/^## (.+)/);
    const h3Match = line.match(/^### (.+)/);

    const headingMatch = h1Match || h2Match || h3Match;
    const headingLevel = h1Match ? 1 : h2Match ? 2 : h3Match ? 3 : 0;

    if (headingMatch && headingLevel > 0) {
      // Save previous section
      if (currentTitle) {
        const fullContent = currentLines.join("\n");
        const bodyLines = currentLines.slice(1); // skip heading line
        sections.push({
          id: slugify(currentTitle) + "-" + sections.length,
          title: currentTitle,
          level: currentLevel,
          content: fullContent,
          body: bodyLines.join("\n").trim(),
        });
      } else if (currentLines.length > 0) {
        // Preamble (content before first heading)
        preambleLines = [...currentLines];
        hasPreamble = true;
      }

      currentTitle = headingMatch[1].trim();
      currentLevel = headingLevel;
      currentLines = [line];
    } else {
      currentLines.push(line);
    }
  }

  // Save last section
  if (currentTitle) {
    const fullContent = currentLines.join("\n");
    const bodyLines = currentLines.slice(1);
    sections.push({
      id: slugify(currentTitle) + "-" + sections.length,
      title: currentTitle,
      level: currentLevel,
      content: fullContent,
      body: bodyLines.join("\n").trim(),
    });
  } else if (currentLines.length > 0 && !hasPreamble) {
    preambleLines = [...currentLines];
    hasPreamble = true;
  }

  // If there's preamble content, add it as first "section"
  if (hasPreamble && preambleLines.some((l) => l.trim())) {
    sections.unshift({
      id: "preamble-0",
      title: "Introduction",
      level: 1,
      content: preambleLines.join("\n"),
      body: preambleLines.join("\n").trim(),
    });
  }

  return sections;
}

/**
 * Reassemble full markdown from edited sections.
 */
function reassembleSections(sections: ParsedSection[]): string {
  return sections.map((s) => s.content.trimEnd()).join("\n\n") + "\n";
}

// Auto-generated section titles that should be non-editable
const AUTO_GENERATED_TITLES = [
  "valuation summary",
  "traq risk assessment",
  "limiting conditions",
  "arborist certification",
  "certification statement",
  "tree inventory",
];

function isAutoGenerated(title: string): boolean {
  const lower = title.toLowerCase();
  return AUTO_GENERATED_TITLES.some((t) => lower.includes(t));
}

// ---------------------------------------------------------------------------
// Photo thumbnail injection
// ---------------------------------------------------------------------------

function getTreePhotosHtml(treeNumber: number, trees: TreeRecord[]): string {
  const tree = trees.find((t) => t.treeNumber === treeNumber);
  if (!tree?.treePhotos?.length) return "";
  const photos = tree.treePhotos.slice(0, 4);
  const extra = (tree.treePhotos.length || 0) - 4;
  const thumbs = photos
    .map(
      (p) =>
        `<img src="${p.url}" alt="${p.caption || ""}" style="width:80px;height:80px;object-fit:cover;border-radius:4px;border:1px solid #e5e4df;" />`
    )
    .join("");
  const overflow = extra > 0 ? `<span style="font-size:11px;color:#999;margin-left:4px;">+${extra} more</span>` : "";
  return `<div style="display:flex;gap:6px;align-items:center;margin:8px 0 12px;">${thumbs}${overflow}</div>`;
}

// ---------------------------------------------------------------------------
// Section Card Component
// ---------------------------------------------------------------------------

function SectionCard({
  section,
  trees,
  reportId,
  editingId,
  onStartEdit,
  onSave,
  onCancel,
  readOnly,
}: {
  section: ParsedSection;
  trees: TreeRecord[];
  reportId: string;
  editingId: string | null;
  onStartEdit: (id: string) => void;
  onSave: (id: string, newBody: string) => void;
  onCancel: () => void;
  readOnly?: boolean;
}) {
  const { toast } = useToast();
  const isEditing = editingId === section.id;
  const isOtherEditing = editingId !== null && editingId !== section.id;
  const autoGenerated = isAutoGenerated(section.title);

  // Edit state
  const [editBody, setEditBody] = useState(section.body);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // AI rewrite state
  const [showRewrite, setShowRewrite] = useState(false);
  const [rewriteInstruction, setRewriteInstruction] = useState("");
  const [rewriting, setRewriting] = useState(false);
  const [rewriteResult, setRewriteResult] = useState<string | null>(null);

  // Auto-generated section collapse
  const [collapsed, setCollapsed] = useState(autoGenerated);

  // Sync editBody when section changes
  useEffect(() => {
    setEditBody(section.body);
  }, [section.body]);

  // Auto-focus textarea on edit
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus();
      // Auto-resize
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = textareaRef.current.scrollHeight + "px";
    }
  }, [isEditing]);

  // Extract tree number from heading for photo thumbnails
  const treeMatch = section.title.match(/Tree #(\d+)/);
  const treeNumber = treeMatch ? parseInt(treeMatch[1]) : null;

  // Render section HTML
  const sectionHtml = renderMarkdownToHtml(section.body);
  const photoHtml = treeNumber ? getTreePhotosHtml(treeNumber, trees) : "";

  const handleRewrite = async () => {
    if (!rewriteInstruction.trim()) return;
    setRewriting(true);
    try {
      const res = await fetch("/api/ai/rewrite-section", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          reportId,
          sectionTitle: section.title,
          sectionContent: section.content,
          instruction: rewriteInstruction,
        }),
      });
      if (!res.ok) throw new Error("Failed to rewrite section");
      const data = await res.json();
      // Strip the heading from the result if present
      const resultLines = (data.content as string).split("\n");
      const firstLine = resultLines[0];
      const hasHeading = /^#{1,3} /.test(firstLine);
      const newBody = hasHeading ? resultLines.slice(1).join("\n").trim() : data.content.trim();
      setRewriteResult(newBody);
    } catch (err) {
      console.error("Rewrite error:", err);
      toast({
        title: "Rewrite failed",
        description: "Could not rewrite this section. Please try again.",
        variant: "destructive",
      });
    } finally {
      setRewriting(false);
    }
  };

  const acceptRewrite = () => {
    if (rewriteResult !== null) {
      onSave(section.id, rewriteResult);
      setRewriteResult(null);
      setShowRewrite(false);
      setRewriteInstruction("");
    }
  };

  const rejectRewrite = () => {
    setRewriteResult(null);
  };

  // Heading tag
  const HeadingTag = section.level === 1 ? "h1" : section.level === 2 ? "h2" : "h3";

  return (
    <div
      id={`section-${section.id}`}
      className={`group relative rounded-lg border transition-colors ${
        isEditing
          ? "border-forest/40 bg-white shadow-sm"
          : isOtherEditing
            ? "border-neutral-100 bg-neutral-50/50 opacity-60"
            : "border-neutral-200/60 bg-white hover:border-neutral-300"
      }`}
    >
      {/* Section heading + action buttons */}
      <div className="flex items-start justify-between px-5 pt-4 pb-1">
        <button
          type="button"
          onClick={autoGenerated ? () => setCollapsed(!collapsed) : undefined}
          className={`flex items-center gap-2 text-left ${autoGenerated ? "cursor-pointer" : "cursor-default"}`}
        >
          {autoGenerated && (
            collapsed
              ? <ChevronRight className="h-4 w-4 text-neutral-400 shrink-0 mt-0.5" />
              : <ChevronDown className="h-4 w-4 text-neutral-400 shrink-0 mt-0.5" />
          )}
          <HeadingTag
            className={`font-display font-semibold tracking-tight ${
              section.level === 1
                ? "text-base text-forest"
                : section.level === 2
                  ? "text-[15px] text-forest"
                  : "text-sm text-neutral-800"
            }`}
          >
            {section.title}
          </HeadingTag>
          {autoGenerated && (
            <span className="text-[10px] text-neutral-400 bg-neutral-100 px-1.5 py-0.5 rounded ml-2">
              Auto-generated
            </span>
          )}
        </button>

        {/* Action buttons — visible on hover */}
        {!readOnly && !autoGenerated && !isEditing && !isOtherEditing && !showRewrite && (
          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
            <button
              type="button"
              onClick={() => {
                setEditBody(section.body);
                onStartEdit(section.id);
              }}
              className="flex items-center gap-1 text-xs text-neutral-500 hover:text-forest px-2 py-1 rounded hover:bg-forest/5 transition-colors"
            >
              <Pencil className="h-3 w-3" />
              Edit
            </button>
            <button
              type="button"
              onClick={() => setShowRewrite(true)}
              className="flex items-center gap-1 text-xs text-neutral-500 hover:text-violet-600 px-2 py-1 rounded hover:bg-violet-50 transition-colors"
            >
              <Sparkles className="h-3 w-3" />
              AI Rewrite
            </button>
          </div>
        )}
      </div>

      {/* Auto-generated collapsed */}
      {autoGenerated && collapsed && (
        <div className="px-5 pb-3">
          <p className="text-xs text-neutral-400 italic">
            Click to expand. This section is generated from your assessment data.
          </p>
        </div>
      )}

      {/* Section content */}
      {(!autoGenerated || !collapsed) && (
        <div className="px-5 pb-4">
          {/* Photo thumbnails for tree sections */}
          {photoHtml && !isEditing && (
            <div dangerouslySetInnerHTML={{ __html: photoHtml }} />
          )}

          {isEditing ? (
            /* ---- Edit Mode ---- */
            <div className="space-y-3">
              <Textarea
                ref={textareaRef}
                value={editBody}
                onChange={(e) => {
                  setEditBody(e.target.value);
                  // Auto-resize
                  e.target.style.height = "auto";
                  e.target.style.height = e.target.scrollHeight + "px";
                }}
                className="font-mono text-sm leading-relaxed resize-none min-h-[120px] border-neutral-200"
                spellCheck={false}
              />
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  onClick={() => onSave(section.id, editBody)}
                  className="bg-forest hover:bg-forest-light"
                >
                  <Check className="h-3.5 w-3.5 mr-1" />
                  Save
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={onCancel}
                >
                  <X className="h-3.5 w-3.5 mr-1" />
                  Cancel
                </Button>
              </div>
            </div>
          ) : rewriteResult !== null ? (
            /* ---- Rewrite Result (diff-like view) ---- */
            <div className="space-y-3">
              <div className="rounded border border-neutral-200 bg-neutral-50 p-3 opacity-50">
                <p className="text-[10px] text-neutral-400 uppercase tracking-wider mb-1 font-semibold">Original</p>
                <div
                  className="prose prose-sm max-w-none text-neutral-500 report-section-content"
                  dangerouslySetInnerHTML={{ __html: renderMarkdownToHtml(section.body) }}
                />
              </div>
              <div className="rounded border border-forest/30 bg-forest/5 p-3">
                <p className="text-[10px] text-forest uppercase tracking-wider mb-1 font-semibold">Rewritten</p>
                <div
                  className="prose prose-sm max-w-none report-section-content"
                  dangerouslySetInnerHTML={{ __html: renderMarkdownToHtml(rewriteResult) }}
                />
              </div>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  onClick={acceptRewrite}
                  className="bg-forest hover:bg-forest-light"
                >
                  <Check className="h-3.5 w-3.5 mr-1" />
                  Accept
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={rejectRewrite}
                >
                  <Undo2 className="h-3.5 w-3.5 mr-1" />
                  Reject
                </Button>
              </div>
            </div>
          ) : (
            /* ---- Read Mode ---- */
            <div
              className="prose prose-sm max-w-none report-section-content"
              style={{
                fontFamily: "'Roboto', sans-serif",
                fontSize: "10.5pt",
                lineHeight: 1.55,
                color: "#3A3A36",
              }}
              dangerouslySetInnerHTML={{ __html: sectionHtml }}
            />
          )}

          {/* AI Rewrite instruction input */}
          {showRewrite && rewriteResult === null && (
            <div className="mt-3 space-y-2 p-3 rounded-lg border border-violet-200 bg-violet-50/50">
              <label className="text-xs font-semibold text-violet-700">
                What should change in this section?
              </label>
              <Input
                value={rewriteInstruction}
                onChange={(e) => setRewriteInstruction(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleRewrite();
                  }
                }}
                placeholder="e.g. Make it more concise, add more detail about root health, soften the language..."
                className="text-sm"
                disabled={rewriting}
                autoFocus
              />
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  onClick={handleRewrite}
                  disabled={rewriting || !rewriteInstruction.trim()}
                  className="bg-violet-600 hover:bg-violet-700"
                >
                  {rewriting ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" />
                      Rewriting...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3.5 w-3.5 mr-1" />
                      Rewrite
                    </>
                  )}
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => {
                    setShowRewrite(false);
                    setRewriteInstruction("");
                  }}
                  disabled={rewriting}
                >
                  Cancel
                </Button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main SectionEditor Component
// ---------------------------------------------------------------------------

export function SectionEditor({
  content,
  reportId,
  trees,
  onContentChange,
  readOnly = false,
}: SectionEditorProps) {
  const [sections, setSections] = useState<ParsedSection[]>(() =>
    parseIntoSections(content)
  );
  const [editingId, setEditingId] = useState<string | null>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // Re-parse when content changes externally
  useEffect(() => {
    setSections(parseIntoSections(content));
  }, [content]);

  const handleStartEdit = useCallback((id: string) => {
    setEditingId(id);
  }, []);

  const handleSave = useCallback(
    (id: string, newBody: string) => {
      const updated = sections.map((s) => {
        if (s.id !== id) return s;
        // Rebuild the heading line
        const headingPrefix = "#".repeat(s.level);
        // For preamble sections without a real heading
        const isPreamble = s.id.startsWith("preamble-");
        const newContent = isPreamble
          ? newBody
          : `${headingPrefix} ${s.title}\n\n${newBody}`;
        return { ...s, body: newBody, content: newContent };
      });
      setSections(updated);
      setEditingId(null);
      onContentChange(reassembleSections(updated));
    },
    [sections, onContentChange]
  );

  const handleCancel = useCallback(() => {
    setEditingId(null);
  }, []);

  // Scroll to a section by id
  const scrollToSection = useCallback((sectionId: string) => {
    const el = document.getElementById(`section-${sectionId}`);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, []);

  // Build section nav from current sections
  const editableSections = sections.filter((s) => !isAutoGenerated(s.title));
  const autoSections = sections.filter((s) => isAutoGenerated(s.title));

  return (
    <div className="flex-1 flex overflow-hidden">
      {/* Section Navigation — hidden on mobile */}
      <div className="hidden md:flex flex-none w-[280px] min-w-[280px] border-r bg-muted/30 overflow-hidden flex-col">
        <div className="px-4 py-3 border-b">
          <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
            Sections
          </span>
        </div>
        <ScrollArea className="flex-1">
          <div className="p-2 space-y-0.5">
            {sections.map((section) => (
              <button
                key={section.id}
                onClick={() => scrollToSection(section.id)}
                className={`w-full text-left text-xs px-3 py-2 rounded hover:bg-accent transition-colors leading-snug ${
                  section.level === 1
                    ? "font-semibold text-foreground"
                    : section.level === 2
                      ? "pl-5 text-muted-foreground"
                      : "pl-7 text-muted-foreground/70"
                } ${isAutoGenerated(section.title) ? "italic opacity-60" : ""}`}
              >
                {section.title}
              </button>
            ))}
          </div>
        </ScrollArea>
      </div>

      {/* Section Cards */}
      <div ref={scrollContainerRef} className="flex-1 overflow-y-auto">
        <div className="mx-auto py-6 px-4 sm:px-6 space-y-3" style={{ maxWidth: "800px" }}>
          {/* Report section styles */}
          <style>{`
            .report-section-content h1,
            .report-section-content h2,
            .report-section-content h3 {
              color: #1D4E3E;
              font-family: 'Instrument Sans', sans-serif;
            }
            .report-section-content h1 {
              font-size: 14pt;
              font-weight: 700;
              border-bottom: 2.5px solid #1D4E3E;
              padding-bottom: 6px;
              margin-bottom: 12px;
            }
            .report-section-content h2 {
              font-size: 12pt;
              font-weight: 600;
              border-bottom: 1px solid #e5e4df;
              padding-bottom: 4px;
              margin-bottom: 10px;
            }
            .report-section-content h3 {
              font-size: 10.5pt;
              font-weight: 600;
              color: #333;
              margin-bottom: 8px;
            }
            .report-section-content table {
              width: 100%;
              border-collapse: collapse;
              font-size: 0.8rem;
            }
            .report-section-content table th {
              background: #1D4E3E;
              color: white;
              padding: 6px 10px;
              text-align: left;
              font-size: 8.5pt;
              letter-spacing: 0.3px;
            }
            .report-section-content table td {
              padding: 6px 10px;
              border-bottom: 1px solid #e5e4df;
            }
            .report-section-content table tr:nth-child(even) {
              background: #FEFDFB;
            }
            .report-section-content hr {
              border: none;
              border-top: 1px solid #e5e4df;
              margin: 16px 0;
            }
            .report-section-content p {
              margin-bottom: 8px;
            }
            .report-section-content ul,
            .report-section-content ol {
              margin-bottom: 8px;
              padding-left: 1.5em;
            }
            .report-section-content li {
              margin-bottom: 2px;
            }
          `}</style>

          {editableSections.map((section) => (
            <SectionCard
              key={section.id}
              section={section}
              trees={trees}
              reportId={reportId}
              editingId={editingId}
              onStartEdit={handleStartEdit}
              onSave={handleSave}
              onCancel={handleCancel}
              readOnly={readOnly}
            />
          ))}

          {/* Auto-generated sections divider */}
          {autoSections.length > 0 && (
            <>
              <div className="flex items-center gap-3 py-2">
                <div className="flex-1 border-t border-neutral-200" />
                <span className="text-[11px] text-neutral-400 font-medium whitespace-nowrap">
                  Auto-Generated Sections (included in final PDF)
                </span>
                <div className="flex-1 border-t border-neutral-200" />
              </div>
              {autoSections.map((section) => (
                <SectionCard
                  key={section.id}
                  section={section}
                  trees={trees}
                  reportId={reportId}
                  editingId={editingId}
                  onStartEdit={handleStartEdit}
                  onSave={handleSave}
                  onCancel={handleCancel}
                  readOnly={readOnly}
                />
              ))}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
